### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by mmiszy** [andresz1/size-limit-action#22]
Full log is available here: https://github.com/typeofweb/devfaq-www/runs/728302480

```
(node:3104) UnhandledPromiseRejectionWarning: HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/andresz1/size-limit-action/v1.3.1/dist/index.js:10628:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:3104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by andresz1** [comment]
Hi @mmiszy,

Thank you for opening an issue! I'll do some investigation and come back to you with more information!

**Comment by andresz1** [comment]
Hi @mmiszy! just checked this [PR](https://github.com/typeofweb/devfaq-www/pull/48) and it seems like it's working as expected 🤔  can you check and let me know please ?

Thanks in advance!

**Comment by mmiszy** [comment]
I think you'll want to have Unhandled Promise Rejection fixed anyway :)

I did some digging and it seems that there's a difference between these two build: The first one (which failed) was triggered by a PR from a fork of this repository, while the second one is my own PR to my own repo. Maybe that's the problem?

**Comment by mmiszy** [comment]
Okay, so that's a thing: https://github.community/t/github-actions-are-severely-limited-on-prs/18179/8

**Comment by andresz1** [comment]
Thank you for the investigation @mmiszy. Now I remember that it also happened to me and that's the reason why I added this log `Error creating PR review. This can happen for PR's originating from a fork without write permissions.`. Any idea to find a workaround ? I haven't found anything yet 😞

**Comment by simonireilly** [comment]
If you still encounter this issue it is because the GITHUB_TOKEN does not have sufficient privileges to write the comment out after running.

The fix is to allow repo writing in the github action token.
